"""user prefs

Revision ID: 242679cd3bc1
Revises: c4311a2f284a
Create Date: 2021-09-22 13:21:59.970145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242679cd3bc1'
down_revision = 'c4311a2f284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score_calculation_method', sa.Enum('AVERAGE', 'HIGHEST', 'HIGH_LAST_AVERAGE', name='masterycalculation'), nullable=True),
    sa.Column('mastery_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_preferences_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
