"""rename outcome attempt table

Revision ID: 28252c773da0
Revises: a687638aff64
Create Date: 2021-09-16 15:46:55.868546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28252c773da0'
down_revision = 'a687638aff64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], name=op.f('fk_outcome_attempt_outcome_id_outcome'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_outcome_attempt_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome_attempt'))
    )
    op.drop_table('user_outcomes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('outcome_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('occurred', sa.DATETIME(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], name='fk_user_outcomes_outcome_id_outcome', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_outcomes_user_id_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_outcomes')
    )
    op.drop_table('outcome_attempt')
    # ### end Alembic commands ###
