"""constraints on OA.attempt_id

Revision ID: 34067c28e871
Revises: 8ff9163ae9b3
Create Date: 2021-09-20 14:10:08.430620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34067c28e871'
down_revision = '8ff9163ae9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_outcome_attempt_attempt_id'), ['attempt_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_outcome_attempt_attempt_id'), type_='unique')
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
