"""unique constrain on assignments, outcomes

Revision ID: 71015f3e67ad
Revises: a2b3fb901b44
Create Date: 2021-09-16 12:02:14.827656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71015f3e67ad'
down_revision = 'a2b3fb901b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_assignment_canvas_id'), ['canvas_id'])

    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_outcome_canvas_id'), ['canvas_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_outcome_canvas_id'), type_='unique')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_assignment_canvas_id'), type_='unique')

    # ### end Alembic commands ###
