"""rename outcome attempt attributes for clarity

Revision ID: 7848d1d48dbb
Revises: 10dcfa90976e
Create Date: 2021-12-17 13:30:27.599090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7848d1d48dbb'
down_revision = '10dcfa90976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_outcome_attempt')
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_canvas_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outcome_canvas_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attempt_canvas_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_outcome_attempt_attempt_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_outcome_attempt_attempt_canvas_id'), ['attempt_canvas_id'])
        batch_op.drop_constraint('fk_outcome_attempt_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_outcome_attempt_outcome_id_outcome', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_outcome_attempt_outcome_canvas_id_outcome'), 'outcome', ['outcome_canvas_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_outcome_attempt_user_canvas_id_user'), 'user', ['user_canvas_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('outcome_id')
        batch_op.drop_column('attempt_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('attempt_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('outcome_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_outcome_attempt_user_canvas_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_outcome_attempt_outcome_canvas_id_outcome'), type_='foreignkey')
        batch_op.create_foreign_key('fk_outcome_attempt_outcome_id_outcome', 'outcome', ['outcome_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_outcome_attempt_user_id_user', 'user', ['user_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_outcome_attempt_attempt_canvas_id'), type_='unique')
        batch_op.create_unique_constraint('uq_outcome_attempt_attempt_id', ['attempt_id'])
        batch_op.drop_column('attempt_canvas_id')
        batch_op.drop_column('outcome_canvas_id')
        batch_op.drop_column('user_canvas_id')

    op.create_table('_alembic_tmp_outcome_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_canvas_id', sa.INTEGER(), nullable=True),
    sa.Column('outcome_canvas_id', sa.INTEGER(), nullable=True),
    sa.Column('attempt_canvas_id', sa.INTEGER(), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('occurred', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['outcome_canvas_id'], ['outcome.canvas_id'], name='fk_outcome_attempt_outcome_canvas_id_outcome', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_canvas_id'], ['user.canvas_id'], name='fk_outcome_attempt_user_canvas_id_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_outcome_attempt'),
    sa.UniqueConstraint('attempt_canvas_id', name='uq_outcome_attempt_attempt_canvas_id')
    )
    # ### end Alembic commands ###
