"""look up outcome attempt by canvas_id

Revision ID: 8ab6aa1b64c9
Revises: 34067c28e871
Create Date: 2021-09-20 14:59:37.066501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab6aa1b64c9'
down_revision = '34067c28e871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outcome_attempt_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_outcome_attempt_user_id_user'), 'user', ['user_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_outcome_attempt_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_outcome_attempt_user_id_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
