"""add OA canvas_id to model

Revision ID: 8ff9163ae9b3
Revises: f720db372ad1
Create Date: 2021-09-20 14:08:48.911030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff9163ae9b3'
down_revision = 'f720db372ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_assignment_assignment_id_outcome', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_assignment_assignment_id_assignment'), 'assignment', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_assignment_assignment_id_assignment'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_assignment_assignment_id_outcome', 'outcome', ['assignment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_column('attempt_id')

    # ### end Alembic commands ###
