"""handle enrollments for users

Revision ID: 914892f357c3
Revises: 71015f3e67ad
Create Date: 2021-09-16 13:07:22.269551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914892f357c3'
down_revision = '71015f3e67ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_canvas_id'), ['canvas_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_canvas_id'), type_='unique')

    # ### end Alembic commands ###
