"""use an association object for attempts

Revision ID: a687638aff64
Revises: 942761f691bb
Create Date: 2021-09-16 14:13:09.943537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687638aff64'
down_revision = '942761f691bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))
        batch_op.drop_column('successful')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('successful', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('success')

    # ### end Alembic commands ###
