"""look fix broken foreign key

Revision ID: c4311a2f284a
Revises: 8ab6aa1b64c9
Create Date: 2021-09-20 15:04:53.418722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4311a2f284a'
down_revision = '8ab6aa1b64c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outcome_attempt_outcome_id_outcome', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_outcome_attempt_outcome_id_outcome'), 'outcome', ['outcome_id'], ['canvas_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_outcome_attempt_outcome_id_outcome'), type_='foreignkey')
        batch_op.create_foreign_key('fk_outcome_attempt_outcome_id_outcome', 'outcome', ['outcome_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
