"""user_assignment as association object

Revision ID: d9455f3ed110
Revises: 28252c773da0
Create Date: 2021-09-16 16:21:56.674779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9455f3ed110'
down_revision = '28252c773da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['outcome.id'], name=op.f('fk_user_assignment_assignment_id_outcome'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_assignment_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_assignment'))
    )
    op.drop_table('user_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('occurred', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['outcome.id'], name='fk_user_assignments_assignment_id_outcome', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_assignments_user_id_user', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_assignments')
    )
    op.drop_table('user_assignment')
    # ### end Alembic commands ###
