"""course assignments association

Revision ID: f720db372ad1
Revises: d9455f3ed110
Create Date: 2021-09-16 16:24:51.607524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f720db372ad1'
down_revision = 'd9455f3ed110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('assignmend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignmend_id'], ['assignment.id'], name=op.f('fk_course_assignments_assignmend_id_assignment'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_assignments_course_id_course'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_assignments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_assignments')
    # ### end Alembic commands ###
