"""float mastery score

Revision ID: fe2a2e4e0e34
Revises: e00e7c1436a2
Create Date: 2022-10-07 13:45:28.012462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe2a2e4e0e34'
down_revision = 'e00e7c1436a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('mastery_score',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.FLOAT(precision=2, scale=1),
               existing_nullable=True,
               existing_server_default=sa.text("'3'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('mastery_score',
               existing_type=mysql.FLOAT(precision=2, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True,
               existing_server_default=sa.text("'3'"))

    # ### end Alembic commands ###
